name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

    #  - name: Build with Gradle
    #    run: ./gradlew build

      - name: Test with Gradle
        run: ./gradlew test --tests "cz.vektor330.ImageResizeHandlerTest"

    # Uncomment the following step if you want to run integration tests
    # Note: You'll need to set up AWS credentials as secrets in your GitHub repository
    # - name: Run integration tests
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     AWS_REGION: us-west-2  # Replace with your AWS region
    #   run: ./gradlew test --tests "cz.vektor330.LambdaIntegrationTest"
